function Point = find_bodyPart(BodyPartsNames)

% Списки возможных названий для каждой части тела
BodyPartsNamesMap = struct(...
    'MiniscopeUCLA', {{'miniscopeUCLA'}}, ...
    'Nose', {{'nose', 'Nose'}}, ...
    'LeftEar', {{'leftear'}}, ...
    'RightEar', {{'rightear'}}, ...
    'HeadCenter', {{'headcenter'}}, ...
    'LeftForeLimb', {{'leftforelimb'}}, ...
    'RightForeLimb', {{'righforelimb'}}, ...
    'LeftBodyCenter', {{'leftbody'}}, ...
    'RightBodyCenter', {{'rightbody'}}, ...
    'LeftHindLimb', {{'lefthindlimb'}}, ...
    'RightHindLimb', {{'righthindlimb'}}, ...
    'Tailbase', {{'tailbase', 'Tailbase', 'Tail base', 'tail base'}}, ...
    'Center', {{'mass centre', 'mass center', 'bodycenter', 'center'}} ...
);

% Инициализация структуры результата
Point = struct();

% Поиск индексов для каждого списка названий
fields = fieldnames(BodyPartsNamesMap);
for i = 1:numel(fields)
    bodyPartField = fields{i};
    bodyPartNames = BodyPartsNamesMap.(bodyPartField);
    
    % Находим индекс первого совпадения
    idx = find(ismember(lower(BodyPartsNames), lower(bodyPartNames)), 1);
    
    % Записываем результат
    Point.(bodyPartField) = idx;
end

end
