function params = actParams()
% ACTPARAMS  Map of act names to the metric fields collected per act.
%
%   params = sphynx.acts.actParams() returns a struct where each field
%   is an act name and each value is a string array of metric names
%   ("ActPercent", "ActNumber", "ActMeanTime", "Distance", ...) that
%   should be reported in the SuperTable for that act.
%
%   Ported from legacy functions/behavior_act_params.m. The full list
%   includes velocity acts, space acts, NOF/LNOF/HOS object acts, BOF
%   bowl acts, BOWL acts, 2DM acts, and 3DM acts.
%
%   Used by sphynx.pipeline.runBatch (Pass C) to assemble the
%   per-experiment SuperTable.

    params = struct( ...
        ... % --- velocity acts ---
        'rest',                       ["ActNumber" "ActPercent"], ...
        'walk',                       ["ActNumber" "ActPercent"], ...
        'locomotion',                 ["ActNumber" "ActPercent"], ...
        ... % --- space acts ---
        'walls',                      ["ActPercent" "Distance"], ...
        'middle_zone',                ["ActPercent" "Distance"], ...
        'center',                     ["ActNumber" "ActPercent" "Distance"], ...
        'corners',                    "ActPercent", ...
        ... % --- unspecific ---
        'freezing',                   "ActPercent", ...
        'rear',                       "ActNumber", ...
        ... % --- NOF/LNOF/HOS ---
        'object1',                    ["ActDuration" "ActPercent"], ...
        'object2',                    ["ActDuration" "ActPercent"], ...
        'object3',                    ["ActDuration" "ActPercent"], ...
        'object4',                    ["ActDuration" "ActPercent"], ...
        'objects',                    ["ActDuration" "ActPercent"], ...
        'object_interaction',         ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'entry_in_object',            "ActNumber", ...
        'object_in_view',             "ActPercent", ...
        ... % --- BOF (old names) ---
        'bowlinside',                 ["ActDuration" "ActPercent"], ...
        'bowlinteraction',            ["ActDuration" "ActPercent"], ...
        'bowlinteractreal',           ["ActDuration" "ActPercent"], ...
        'entryInBowlInside',          "ActNumber", ...
        'entryInBowlInteract',        "ActNumber", ...
        'entryInBowlInsideAll',       "ActNumber", ...
        'entryInBowlInteractAll',     "ActNumber", ...
        'entryOutBowlInside',         "ActNumber", ...
        'entryOutBowlInteract',       "ActNumber", ...
        'entryOutBowlInsideAll',      "ActNumber", ...
        'entryOutBowlInteractAll',    "ActNumber", ...
        'bowlInView',                 "ActPercent", ...
        ... % --- BOF object acts (old names) ---
        'objectinside',               ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'objectinteraction',          ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'objectinteractreal',         ["ActDuration" "ActPercent"], ...
        'entryInObjectInside',        "ActNumber", ...
        'entryInObjectInteract',      "ActNumber", ...
        'entryInObjectInsideAll',     "ActNumber", ...
        'entryInObjectInteractAll',   "ActNumber", ...
        'entryOutObjectInside',       "ActNumber", ...
        'entryOutObjectInteract',     "ActNumber", ...
        'entryOutObjectInsideAll',    "ActNumber", ...
        'entryOutObjectnteractAll',   "ActNumber", ...
        'objectInView',               "ActPercent", ...
        ... % --- BOWL (new names) ---
        'bowl_interaction',           ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'object1_interaction',        ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'object2_interaction',        ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'bowl_inside',                ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'object1_inside',             ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'object2_inside',             ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'entry_in_bowl',              "ActNumber", ...
        'entry_in_object1',           "ActNumber", ...
        'entry_in_object2',           "ActNumber", ...
        'bowl_in_view',               "ActPercent", ...
        'object1_in_view',            "ActPercent", ...
        'object2_in_view',            "ActPercent", ...
        ... % --- 2DM ---
        'rest_in_walls',              "ActNumber", ...
        'loc_in_walls',               "ActNumber", ...
        'rest_in_middle_zone',        "ActNumber", ...
        'loc_in_middle_zone',         "ActNumber", ...
        'rest_in_center',             "ActNumber", ...
        'loc_in_center',              "ActNumber", ...
        ... % --- 3DM ---
        'start_box',                  ["ActNumber" "ActPercent"], ...
        'arms',                       ["ActNumber" "ActPercent" "Distance"], ...
        'straight_arms',              ["ActNumber" "ActPercent" "Distance"], ...
        'sloping_arms',               ["ActNumber" "ActPercent" "Distance"], ...
        'slope_down_arms',            ["ActNumber" "ActPercent" "Distance"], ...
        'slope_up_arms',              ["ActNumber" "ActPercent" "Distance"], ...
        'box_upper',                  ["ActPercent" "Distance"], ...
        'box_middle',                 ["ActPercent" "Distance"], ...
        'box_lower',                  ["ActPercent" "Distance"], ...
        'mouse_goes_straight',        ["ActPercent" "Distance"], ...
        'mouse_goes_up',              ["ActPercent" "Distance"], ...
        'mouse_goes_down',            ["ActPercent" "Distance"], ...
        ... % --- NOL ---
        'object_control_inside',      ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"], ...
        'object_control_interaction', ["ActNumber" "ActDuration" "ActPercent" "ActMeanTime"]);
end
