path = 'g:\_Projects\_OF [2023]\VT\VT_original\Part2D2\';
pathout = 'g:\_Projects\_OF [2023]\VT\Part2D2\';
filenames = {
    'Trial    25.mpg','Trial    26.mpg','Trial    27.mpg','Trial    28.mpg',...  
    'Trial    29.mpg','Trial    30.mpg','Trial    31.mpg','Trial    32.mpg',...
    'Trial    33.mpg','Trial    34.mpg','Trial    35.mpg','Trial    36.mpg',...
    'Trial    37.mpg','Trial    38.mpg','Trial    39.mpg','Trial    40.mpg',...
    'Trial    41.mpg','Trial    42.mpg','Trial    43.mpg','Trial    44.mpg',...
    'Trial    45.mpg','Trial    46.mpg','Trial    47.mpg','Trial    48.mpg'
};

%%
for video  = 1:length(filenames)
    CroppVideo(path, filenames{video}, pathout, 'division', 480)
end
